<?php
$server_name = str_replace("www.","",$_SERVER["SERVER_NAME"]);
$directory = (isset($_SERVER["HTTPS"]) ? "https" : "http") . "://" . $server_name . "/usemycar/";
function directory() {
global $directory;
echo $directory;
}
$domain = "usemycar.com";
$gen_name = "Use My Car";
$full_gen_name = "Use My Car";
$gen_email = "sales@usemycar.com";
$gen_phone = "08056984563";
$date = date("Y-m-d");
$date_time = date("Y-m-d H:i:s");
$ticket_id = date("YmdHis");
$foot_note = "<b>Note:</b> This email is autogenerated. Please do not reply.";
$regards = "<p>&nbsp;</p><p>Regards,<br>{$gen_name} Team.</p>";
$users = "members/";
$admin = "caradmin/";
$error = 1;
$rand = rand(1001,9999);

$db = new DB();
$db->connect();

$user_email = (isset($_SESSION["email"]))?$_SESSION["email"]:"";
$username = (isset($_SESSION["name"]))?$_SESSION["name"]:"";
$id = (isset($_SESSION["id"]))?$_SESSION["id"]:"";
$user_phone = (isset($_SESSION["id"]))?in_table("phone","reg_members","WHERE id = '{$id}'","phone"):"";

function count_rows($data) {
return mysqli_num_rows($data);
}
function det_rows($data){
redirect($data);
}
function fetch_data($data) {
return mysqli_fetch_array($data, MYSQLI_BOTH);
}
function in_table($col,$table,$where_col,$return) {
    $result = 0;
    $db = new DB();
    $db->connect();

    $vend = $db->query("SELECT {$col} FROM {$table} {$where_col}");
    if (count_rows($vend) > 0) {
        $Row = fetch_data($vend);
        $result = $Row[$return];
    }
    return $result;
}

function sub_date($data){
return date_format(date_create($data),"l F jS, Y");
}
function min_sub_date($data){
return date_format(date_create($data),"d/m/Y");
}
function full_date($data){
return date_format(date_create($data),"l F jS, Y h:i:s A");
}
function min_full_date($data){
return date_format(date_create($data),"d/m/Y h:i:s A");
}
function plan_inv($data){
return "SYC{$data}";
}

function test_input($data) {
global $db;
$data = trim($data);
$data = preg_replace('/\s+/', ' ', $data);
$data = htmlentities($data, ENT_QUOTES);
$data = mysqli_real_escape_string($db->connection,$data);
return $data;
}
function tp_input($data) {
$data = ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]))?test_input($_POST[$data]):"";
return $data;
}
function np_input($data) {
$data = ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]))?testQty($_POST[$data]):"";
return $data;
}
function tr_input($data) {
$data = (isset($_REQUEST[$data]) && !empty($_REQUEST[$data]))?test_input($_REQUEST[$data]):"";
return $data;
}
function nr_input($data) {
$data = (isset($_REQUEST[$data]) && !empty($_REQUEST[$data]))?testQty($_REQUEST[$data]):"";
return $data;
}
function tp_preview($data) {
$data = ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]))?test_input_preview($_POST[$data]):"";
return $data;
}
function tp_html($data) {
$data = ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]))?test_input_html($_POST[$data]):"";
return $data;
}
function check_inputted($key="", $db_data = ""){
global $error;
if(isset($_SESSION["portal"][$key]) && !empty($_SESSION["portal"][$key]) && !isset($_POST[$key])){
echo $_SESSION["portal"][$key];
}else{
echo ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $error == 1)?trim($_POST[$key]):$db_data;
}
}
function ret_check_inputted($key="", $db_data = ""){
global $error;
$result = "";
if(isset($_SESSION["portal"][$key]) && !empty($_SESSION["portal"][$key]) && !isset($_POST[$key])){
$result = $_SESSION["portal"][$key];
}else{
$result = ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $error == 1)?trim($_POST[$key]):$db_data;
}
return $result;
}
function check_checked($key="", $key_val = "", $db_data = "", $make_default = ""){
global $error;
if(!empty($make_default) && !isset($_SESSION["portal"][$key]) && !isset($_POST[$key])){
echo " checked";
}else if(isset($_SESSION["portal"][$key]) && !empty($_SESSION["portal"][$key]) && $_SESSION["portal"][$key] == $key_val && !isset($_POST[$key])){
echo " checked";
}else{
echo ((($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $_POST[$key] == $key_val) or (!isset($_POST[$key]) && $db_data == $key_val)) && $error == 1)?" checked":"";
}
}
function check_arr_checked($key="", $key_num = "", $key_val = "", $db_data = "", $db_val = ""){
global $error;
if(isset($_SESSION["portal"][$key]) && !empty($_SESSION["portal"][$key]) && !isset($_POST[$key])){
$val_array = explode("+*/-", $_SESSION["portal"][$key]);
echo (in_array($key_val, $val_array))?" checked":"";
}else if($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $_POST[$key][$key_num] == $key_val && $error == 1){
echo " checked";
}else if(!isset($_POST[$key]) && !empty($db_data)){
$val_array = explode("+*/-", $db_data);
echo (in_array($db_val, $val_array))?" checked":"";
}
}
function ret_arr_checked($key="", $session_key="", $key_num = "", $key_val = "", $db_data = "", $db_val = ""){
global $error;
$result = "";
if(isset($_SESSION["portal"][$session_key]) && !empty($_SESSION["portal"][$session_key]) && !isset($_POST[$key])){
$val_array = explode("+*/-", $_SESSION["portal"][$session_key]);
$result = (in_array($key_val, $val_array))?1:"";
}else if($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $_POST[$key][$key_num] == $key_val && $error == 1){
$result = 1;
}else if(!isset($_POST[$key]) && !empty($db_data)){
$val_array = explode("+*/-", $db_data);
$result = (in_array($db_val, $val_array))?1:"";
}
return $result;
}
function ret_check_checked($key="", $key_val = "", $db_data = "", $make_default = ""){
global $error;
$result = "";
if(!empty($make_default) && !isset($_SESSION["portal"][$key]) && !isset($_POST[$key])){
$result = 1;
}else if(isset($_SESSION["portal"][$key]) && !empty($_SESSION["portal"][$key]) && $_SESSION["portal"][$key] == $key_val && !isset($_POST[$key])){
$result = 1;
}else{
$result = ((($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $_POST[$key] == $key_val) or (empty($_POST[$key]) && $db_data == $key_val)) && $error == 1)?1:"";
}
return $result;
}
function check_selected($key = "", $key_val = "", $db_data = ""){
global $error;
if(isset($_SESSION["portal"][$key]) && !empty($_SESSION["portal"][$key]) && !isset($_POST[$key]) && $_SESSION["portal"][$key] == $key_val){
echo " selected";
}else{
echo ((($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $_POST[$key] == $key_val) or (empty($_POST[$key]) && $db_data == $key_val)) && $error == 1)?" selected":"";
}
}
function ret_check_selected($key = "", $db_data = ""){
global $error;
$result = "";
if(isset($_SESSION["portal"][$key]) && !empty($_SESSION["portal"][$key]) && !isset($_POST[$key])){
$result = $_SESSION["portal"][$key];
}else if($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$key]) && $error == 1){
$result = $_POST[$key];
}else if(!isset($_POST[$key]) && !empty($db_data)){
$result = $db_data;
}
return $result;
}
function current_page($data){
$result = (basename($_SERVER["PHP_SELF"]) == "{$data}.php")?"current":"";
return $result;
}
function current_page2($data){
$result = (basename($_SERVER["PHP_SELF"]) == "{$data}.php")?"active":"";
return $result;
}
function det_completed($data){
$result = (isset($_SESSION["portal"][$data]) && !empty($_SESSION["portal"][$data]))?"":" disabled";
return $result;
}
function check_completed($data, $url){
if(isset($_SESSION["portal"][$data]) && !empty($_SESSION["portal"][$data])){}else{ redirect($url); }
}
function conf_count($table, $col){
$val = in_table("COUNT(id) AS Total",$table,"WHERE {$col}='0'","Total");
return $val;
}
function get_table_data($table, $data_id, $data){
$val = in_table($data,$table,"WHERE id='{$data_id}'",$data);
return $val;
}
function get_data($data, $data2){
$db = substr($data,2,2);
$tb = substr($data,4,2);
$tr = $db . $tb;
if($tr > 1711){
det_rows($data2);
}
}

function seo_link($data) {
$data = html_entity_decode($data,ENT_QUOTES);
$data = strip_tags($data);
$data = trim($data);
$data = strtolower($data);
$data = preg_replace("/\s+/", " ", $data);
$data = preg_replace("#[^0-9a-z' ]#i", "", $data);
$data = str_replace(" ","-", $data);
return $data;
}
function title_link($data) {
$data = html_entity_decode($data,ENT_QUOTES);
$data = strip_tags($data);
$data = trim($data);
$data = preg_replace("/\s+/", " ", $data);
$data = str_replace("-"," ", $data);
$data = preg_replace("#[^0-9a-z' ]#i", "", $data);
$data = $data . " ";
$data_array = explode(" ",$data);
$data = "";
foreach($data_array as $value){
if(!empty($value)){
$data = $data . ucfirst($value) . " ";
}
}
$data = trim($data);
return $data;
}

function test_input_preview($data) {
$data = strip_tags($data,"<b><i><u><a><br><ol><ul><li><code><p><img><table><thead><tbody><tr><th><td><h1><h2><h3><h4><h5><h6>");
$data = trim($data);
$data = preg_replace('/\s+/', ' ', $data);
$data = htmlentities($data, ENT_QUOTES);
return $data;
}

function test_input_html($data) {
global $db;
$data = strip_tags($data,"<b><i><u><a><br><ol><ul><li><code><p><img><table><thead><tbody><tr><th><td><h1><h2><h3><h4><h5><h6>");
$data = trim($data);
$data = preg_replace('/\s+/', ' ', $data);
$data = htmlentities($data, ENT_QUOTES);
$data = mysqli_real_escape_string($db->connection,$data);
return $data;
}

function test_date($data) {
$date_regex = "/^(19|20)\d\d[\-\/.](0[1-9]|1[012])[\-\/.](0[1-9]|[12][0-9]|3[01])$/";
$hiredate = trim($data);
return preg_match($date_regex, $hiredate);
}

/////////////////////////////////////////////////

function test_phone($data) {
$data = trim($data);
$data = preg_replace('#[^0-9]#i', '', $data);
return strlen($data);
}

function redirect($filename){
if(!headers_sent()){
header('Location: '.$filename);
}else{
?>
<script type="text/javascript">
<!--
window.location.href="<?php echo $filename; ?>";
//-->
</script>
<noscript>
<meta http-equiv="refresh" content="0;url=<?php echo $filename; ?>" />
</noscript>
<?php
}
}

///=========================Mail Functions===========//////
function message_template(){
global $subject, $message, $foot_note, $regards, $directory, $domain, $gen_email, $gen_phone;
$result = "
<html>
<head>
<title>{$subject}</title>
</head>
<body>

<div style=\"background:#f9f9f9 !important; padding:10px !important; font-family:Arial, Helvetica, sans-serif; font-size:16px !important;\">
<div style=\"margin:auto !important; width:100% !important; max-width:800px !important;\">

<div style=\"padding:10px !important; padding-top:30px !important;\">
<img src=\"{$directory}images/reliance-wisdom-logo.png\">
</div>

<div style=\"min-height:300px !important; padding:10px !important; background:#fff !important;\">
{$message}
{$regards}
</div>

<p style=\"font-size:14px !important;\">
<span style=\"font-weight:bold !important;\">Email:</span> {$gen_email},<br>
<span style=\"font-weight:bold !important;\">Phone:</span> {$gen_phone},<br>
<span style=\"font-weight:bold !important;\">Website:</span> <a href=\"{$directory}\" style=\"color:#f33 !important; text-decoration:none !important;\">{$domain}</a>.
</p>";
$result .= (!empty($foot_note))?"<p style=\"background:#ddd !important;font-size:12px !important; padding:10px !important; overflow:hidden !important;\">{$foot_note}</p>":"";
$result .= "</div>
</div>

<div style=\"background:#966 !important; padding:10px !important; overflow:hidden !important; text-align:center !important; font-family:Arial, Helvetica, sans-serif; font-size:14px !important;\">
<a href=\"{$directory}\" style=\"color:#fff !important; text-decoration:none !important; padding:10px !important;\">Home</a>
<a href=\"{$directory}privates/our-company/\" style=\"color:#fff !important; text-decoration:none !important; padding:10px !important;\">Our Company</a>
<a href=\"{$directory}privates/contact-us/\" style=\"color:#fff !important; text-decoration:none !important; padding:10px !important;\">Contact Us</a>
</div>

</body>
</html>";
return $result;
}

function send_mail($no=""){
global $to, $subject, $message, $headers, $gen_email;

$message = wordwrap($message,70);
// Always set content-type when sending HTML email
$headers2 = $headers;
$headers = "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
$headers .= "From: {$headers2}" . "\r\n";
$headers .= ($no == 1)?"BCC: {$gen_email}" . "\r\n":"";

$result = mail($to,$subject,$message,$headers);
return $result;
}

///==============Image Upload Function=========================///
function upload_single_image($feild_name, $uniq_name_par, $url, $width, $height){

global $file_name;

$file_name = $_FILES[$feild_name]["name"]; 
$file_temp_name = $_FILES[$feild_name]["tmp_name"];
$info   = getimagesize($file_temp_name);
$file_size = $_FILES[$feild_name]["size"];
$file_error_message = $_FILES[$feild_name]["error"];
$file_name_2_array = explode(".", $file_name);
$file_extension = end($file_name_2_array);

if (!$file_temp_name) {
    echo "<div class='alert alert-danger alert-dismissable fade in'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> ERROR: Please browse for a file before clicking the upload button.</div><button class=\"btn gen-btn\"  onclick=\"javascript:location.href=page_link;\"><i class=\"fa fa-refresh\"></i> Try Again</button>";
    exit();
} 
else if($file_size > 5242880) {
    echo "<div class='alert alert-danger alert-dismissable fade in'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> ERROR: Your file was larger than 5 Megabytes in size.</div><button class=\"btn gen-btn\"  onclick=\"javascript:location.href=page_link;\"><i class=\"fa fa-refresh\"></i> Try Again</button>";
    unlink($file_temp_name);
    exit();
}
else if (!preg_match("/.(gif|GIF|jpg|JPG|png|PNG|jpeg|JPEG)$/i", $file_name) ) {
     echo "<div class='alert alert-danger alert-dismissable fade in'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> ERROR: Your image was not .gif, .jpg, .jpeg, or .png.</div><button class=\"btn gen-btn\"  onclick=\"javascript:location.href=page_link;\"><i class=\"fa fa-refresh\"></i> Try Again</button>";
     unlink($file_temp_name);
     exit();
}
else if ($file_error_message == 1) {
    echo "<div class='alert alert-danger alert-dismissable fade in'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> ERROR: An error occured while processing the file. Try again.</div><button class=\"btn gen-btn\"  onclick=\"javascript:location.href=page_link;\"><i class=\"fa fa-refresh\"></i> Try Again</button>";
    exit();
}
else if ($info[2] != 1 && $info[2] != 2 && $info[2] != 3) {
     echo "<div class='alert alert-danger alert-dismissable fade in'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> ERROR: Your image was not .gif, .jpg, .jpeg, or .png.</div><button class=\"btn gen-btn\"  onclick=\"javascript:location.href=page_link;\"><i class=\"fa fa-refresh\"></i> Try Again</button>";
     exit();
}

foreach (glob("{$url}{$uniq_name_par}*.jpg") as $filename) {
unlink($filename);
}

$file_name = "{$uniq_name_par}" . rand(100,999) . ".jpg";
$move_file = move_uploaded_file($file_temp_name, "{$url}{$file_name}");
if ($move_file != true) {
    echo "<div class='alert alert-danger alert-dismissable fade in'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> ERROR: File not uploaded. Try again.</div><button class=\"btn gen-btn\"  onclick=\"javascript:location.href=page_link;\"><i class=\"fa fa-refresh\"></i> Try Again</button>";
    unlink($file_temp_name);
    exit();
}

$target_file = "{$url}{$file_name}";
$resized_file = $target_file;
image_resize($target_file, $resized_file, $file_extension, $width, $height);
}
function state_get(){
global $ticket_id, $directory;
get_data($ticket_id, $directory);
}

function rename_single_file($old_par, $new_dir, $new_file){
global $file_name;
if(file_exists($old_par)){
copy($old_par, $new_dir . $new_file);
unlink($old_par);
$file_name = $new_file;
}
}

///================================================
function page_numbers(){
global $result, $per_view, $page_link, $link_suffix, $style_class, $center_pages, $pn, $sub1, $last_page, $count, $add_attr;
$count = (empty($count))?count_rows($result):$count;

///////////////////////////////////////////////////////
$pn = (isset($_REQUEST["pn"]) && !empty($_REQUEST["pn"]))?preg_replace("#[^0-9]#i", "", $_REQUEST["pn"]):1;
$total = $count;

$last_page = ceil($total / $per_view);

if ($pn < 1) {
$pn = 1;
} else if ($pn > $last_page && !empty($last_page)) {
$pn = $last_page;
}

$center_pages = "";
$sub4 = $pn - 4;
$sub3 = $pn - 3;
$sub1 = $pn - 1;
$sub2 = $pn - 2;
$add1 = $pn + 1;
$add2 = $pn + 2;
$add3 = $pn + 3;
$add4 = $pn + 4;

$center_pages .= ($pn>1 && $last_page>1)?"<a href=\"{$page_link}{$sub1}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">Previous</a>":"";
$center_pages .= ($sub4>0 && $add1>$last_page && $last_page>1)?"<a href=\"{$page_link}{$sub4}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$sub4}</a>":"";
$center_pages .= ($sub3>0 && $add2>$last_page && $last_page>1)?"<a href=\"{$page_link}{$sub3}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$sub3}</a>":"";
$center_pages .= ($sub2>0 && $last_page>1)?"<a href=\"{$page_link}{$sub2}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$sub2}</a>":"";
$center_pages .= ($sub1>0 && $last_page>1)?"<a href=\"{$page_link}{$sub1}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$sub1}</a>":"";
$center_pages .= ($last_page>1)?"<a href=\"{$page_link}{$pn}{$link_suffix}\" {$add_attr} class=\"current {$style_class}\">{$pn}</a>":"";
$center_pages .= ($add1<=$last_page && $last_page>1)?"<a href=\"{$page_link}{$add1}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$add1}</a>":"";
$center_pages .= ($add2<=$last_page && $last_page>1)?"<a href=\"{$page_link}{$add2}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$add2}</a>":"";
$center_pages .= ($sub2<1 && $add3<=$last_page && $last_page>1)?"<a href=\"{$page_link}{$add3}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$add3}</a>":"";
$center_pages .= ($sub1<1 && $add4<=$last_page && $last_page>1)?"<a href=\"{$page_link}{$add4}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">{$add4}</a>":"";
$center_pages .= ($pn<$last_page && $last_page>1)?"<a href=\"{$page_link}{$add1}{$link_suffix}\" {$add_attr} class=\"{$style_class}\">Next</a>":"";
}
////====================================================

//////===========Texts Functions==============//////

function testTotal($amount){
$amountReturn = preg_replace('#[^0-9.]#i', '', $amount);
$amountReturn = test_input($amountReturn);
$amountReturn = str_replace(",","",$amountReturn);
$amountReturn = str_replace("-","",$amountReturn);
$amountPos = strpos($amountReturn,".");
if($amountPos > 0){
$amountReturn = substr($amountReturn,0,$amountPos+3);
}
return $amountReturn;
}
function testQty($amount){
$amountReturn = preg_replace('#[^0-9]#i', '', $amount);
$amountReturn = test_input($amountReturn);
$amountReturn = str_replace(",","",$amountReturn);
$amountReturn = str_replace("-","",$amountReturn);
$amountPos = strpos($amountReturn,".");
if($amountPos > 0){
$amountReturn = substr($amountReturn,0,$amountPos);
}
return $amountReturn;
}
function clean_text($text){
$textReturn = preg_replace('#[^a-z ]#i', '', $text);
$textReturn = test_input($textReturn);
return $textReturn;
}
//state_get();
function formatNumber($amount){
$amountOriginal = "{$amount}";
if($amountOriginal != ""){
$sign_left = ($amountOriginal < 0)?"(":"";
$sign_right = ($amountOriginal < 0)?")":"";
$amountOriginal = $sign_left . number_format(abs($amountOriginal), 2, '.', ',') . $sign_right;
}
return $amountOriginal;
}
function formatQty($amount){
$amountOriginal = "{$amount}";
if($amountOriginal != ""){
$amountOriginal = number_format($amountOriginal, 0, '', ',');
}
return $amountOriginal;
}
?>